name: Deploy para InfinityFree

on:
  push:
    branches:
      - main  # Altere para a branch principal do seu reposit칩rio, se necess치rio

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do C칩digo
        uses: actions/checkout@v3

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: convvet.42web.io  # Substitua pelo seu servidor FTP
          username: if0_37794418
          password: Ux8AitUDBEj
          local-dir: ./  # Altere se precisar enviar apenas uma subpasta
          server-dir: /htdocs/  # Altere para o diret칩rio correto no servidor

